import json
import matplotlib.pyplot as plt
import os

# Read the metrics generated by your successful run
state_path = r"E:\main proj\Cap-Code\lora\lora_unsw_v2\checkpoint-1000\trainer_state.json"
output_path = r"C:\Users\RAHUL\.gemini\antigravity\brain\3b438a76-588d-40ee-9469-c6303929eab0\loss_curve.png"

try:
    with open(state_path, "r", encoding="utf-8") as f:
        data = json.load(f)
except FileNotFoundError:
    print(f"Error: Could not find {state_path}")
    exit(1)

history = data.get("log_history", [])

train_steps = []
train_loss = []
eval_steps = []
eval_loss = []

# Parse the log history array saved by HuggingFace Trainer
for log in history:
    step = log.get("step")
    if "loss" in log:
        train_steps.append(step)
        train_loss.append(log["loss"])
    elif "eval_loss" in log:
        eval_steps.append(step)
        eval_loss.append(log["eval_loss"])

# Plot the graph
plt.figure(figsize=(10, 6))

# Plot training loss as a line
if train_steps and train_loss:
    plt.plot(train_steps, train_loss, label="Training Loss", color="royalblue", alpha=0.8, linewidth=2)

# Plot eval loss with distinct points
if eval_steps and eval_loss:
    plt.plot(eval_steps, eval_loss, label="Evaluation Loss (Unseen Data)", color="darkorange", marker="o", linewidth=2.5, markersize=6)

plt.title("LoRA SFT Training Metrics (Phi-4-mini)", fontsize=14, pad=15)
plt.xlabel("Training Steps", fontsize=12)
plt.ylabel("Loss (Cross Entropy)", fontsize=12)
plt.legend(fontsize=11)
plt.grid(True, linestyle="--", alpha=0.6)

# Improve x-axis integer formatting
plt.gca().xaxis.set_major_locator(plt.MaxNLocator(integer=True))

plt.tight_layout()
plt.savefig(output_path, dpi=300)
print(f"Graph successfully rendered and saved to: {output_path}")
